### ISSUE TITLE
Add locale for cs-CZ

### ISSUE THREAD

**Issue by lauft** [GothenburgBitFactory/holidata#10]
The following locale needs to be verified:
```
class cs_CZ(Locale):
    u"""
    01-01: [NF] Nový rok
    01-01: [NF] Den obnovy samostatnosti českého státu
    05-01: [NF] Svátek práce
    05-08: [NF] Den vítězství
    07-05: [NRF] Den slovanských věrozvěstů
    07-06: [NRF] Den upálení mistra Jana Husa
    09-28: [NRF] Den české státnosti
    10-28: [NF] Den vzniku samostatného československého státu
    11-17: [NF] Den boje za svobodu a demokracii
    12-24: [NRF] Štědrý den
    12-25: [NRF] 1. svátek vánoční
    12-26: [NRF] 2. svátek vánoční
    1 day after Easter: [NRV] Velikonoční pondělí
    """

    locale = "cs-CZ"
    easter_type = 
```
Checklist:
* Are all holidays (i.e. days "which are defined by law on which business or work are suspended or reduced") listed? Can you provide the legal sources which define the holidays?
* Is the spelling correct? Can you maybe provide a translation?
* Are the fixed dates `<month>-<day>` correct?
* If a holiday has a variable date: Is the algorithm to calculate it correct? If it depends on the easter date: Is it the western or orthodox easter date?
* If a holiday is proclaimed by the government: Can you provide the source?
* Are holidays moved to a different date, e.g. if they fall on a saturday/sunday/...? 
* Are holidays observed on a different date (is there a substitute holiday), e.g. if they fall on a saturday/sunday/...?
* Are the flags correct? (`N` = national holiday, defined by law, `R` = holiday with religious background, `F` = holiday with fixed date, `V` = holiday with variable date)

**Comment by igneus** [comment]
The current legal source for holidays in Czech Republic is https://www.zakonyprolidi.cz/cs/2000-245 , §1 and 2.

```python
class cs_CZ(Locale):
    u"""
    01-01: [NF] Nový rok
    01-01: [NF] Den obnovy samostatného českého státu # title fixed
    05-01: [NF] Svátek práce
    05-08: [NF] Den vítězství
    07-05: [NRF] Den slovanských věrozvěstů Cyrila a Metoděje # title fixed
    07-06: [NRF] Den upálení mistra Jana Husa
    09-28: [NRF] Den české státnosti
    10-28: [NF] Den vzniku samostatného československého státu
    11-17: [NF] Den boje za svobodu a demokracii a Mezinárodní den studentstva # title fixed
    12-24: [NRF] Štědrý den
    12-25: [NRF] 1. svátek vánoční
    12-26: [NRF] 2. svátek vánoční
    2 days before Easter: [NRV] Velký pátek # added
    1 day after Easter: [NRV] Velikonoční pondělí
    """

    locale = "cs-CZ"
    easter_type = EASTER_WESTERN # added
```

I left the flags untouched as I haven't found an explanation of their meaning.

**Comment by igneus** [comment]
> Are holidays moved to a different date, e.g. if they fall on a saturday/sunday/...?
> Are holidays observed on a different date (is there a substitute holiday), e.g. if they fall on a saturday/sunday/...?

No.

**Comment by igneus** [comment]
For more or less accurate translations see [this page](https://www.officeholidays.com/countries/czech-republic/2020). If the "Comments" column is populated, it contains the actual translation of the Czech title (while the Holiday Name column seems to contain a customary English name of the holiday).

(As for August 21st already listed there, it's not yet part of the legislation in force.)

**Comment by igneus** [comment]
I'm not completely sure if the `R` flag for `09-28` is correct.
The day as such is a religious feast - day of St. Wenceslas (the very first Czech saint, early 10th c., duke of Bohemia) - but the national holiday (see the name ~ "Day of the Czech statehood") officially celebrates the "secular meaning of this originally religious feast": Wenceslas the Přemyslid duke of Bohemia, Wenceslas as national symbol, not Wenceslas as a Christian saint.

**Comment by lauft** [comment]
> (As for August 21st already listed there, it's not yet part of the legislation in force.)

`08-12` is listed as _important day_ ("Významné dny"). But as stated in §4 (2): _Important days are workdays_ (Významné dny jsou dny pracovními); so we leave it out.

> I'm not completely sure if the R flag for 09-28 is correct.

As the respective law mentions this day as _Day of the Czech statehood_ I would drop the `R` flag.

**Comment by lauft** [comment]
Locale cs-CZ is now available. Data on holidata.net will be updated soon.
Thanks for your contribution!
