### ISSUE TITLE
Holidata.net seams down

### ISSUE THREAD

**Issue by felixschurk** [GothenburgBitFactory/holidata#101]
**Describe the bug**  
When I try to open https://holidata.net, it will always open the website http://ww12.holidata.net/.

**Expected behavior**  
I would expect that it opens the GothenburgBitFactory holidata.net website.

**Additional context**
Pinging the website also results in an error. So I assume that maybe even the domain is no longer available?  
```sh
$ ping https://holidata.net
ping: https://holidata.net: Name or service not known
```
I noticed that when running the script in the taskwarrior repo [update-holidays.pl](https://github.com/GothenburgBitFactory/taskwarrior/blob/8dd29e0a8a2640eecc9b5510a9d252540b2fd146/scripts/add-ons/update-holidays.pl).
However also with the [refresh](https://github.com/GothenburgBitFactory/timewarrior/blob/9f8b0fbc28cc503ade57541b405c78206f97d13c/doc/holidays/refresh) script, I recieve this error:
```sh
$ python3.11 refresh
https://holidata.net/de-DE/2024.json
Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'holidata.net'. (_ssl.c:1006)>
```

**Comment by lauft** [comment]
[holidata.net](https://holidata.net) is back.
