### ISSUE TITLE
Error in locale en-US, year 2024: Day after Thanksgiving

### ISSUE THREAD

**Issue by RogueScholar** [GothenburgBitFactory/holidata#102]
In the [en-US output for this year (2024)](https://holidata.net/en-US/2024.json), the "Day after Thanksgiving" holiday appears to have lost a week in its calculated value, such that it is reported as occurring on the Friday _before_ Thanksgiving (six days prior) rather than the Friday _after_ Thanksgiving (one day in advance).

<details><summary>Relevant contents of the file at time of reporting <i>(click to expand)</i></summary>

```json
{"locale":"en-US","region":"","date":"2024-11-22","description":"Day after Thanksgiving","type":"NV","notes":""}
{"locale":"en-US","region":"","date":"2024-11-28","description":"Thanksgiving Day","type":"NV","notes":""}
```

</details>

The correct date for the **Day after Thanksgiving** in the locale `en-US` in the year 2024 is: **2024-11-29**

Furthermore, no data is published on the site for the upcoming calendar year, 2025. It would be useful were it made so.

**Comment by lauft** [comment]
Thanks for spotting this error. This also affects years 2013 and 2019 where the 4. Friday is not after the 4. Thursday.
