### ISSUE TITLE
Holiday "Mariä Himmelfahrt" missing for region 'BY' in locale 'de-DE'

### ISSUE THREAD

**Issue by sam701** [GothenburgBitFactory/holidata#105]
**Describe the bug**  
* Which locale is affected? 
  * `de-DE`
* Which holidays are affected? 
  * `*-08-15`
* Which years does the bug affect? 
  * All years

**Expected behavior**  
Every year Aug 15 is a holiday in Bavaria (BY), Germany.
The line
```json
{"locale":"de-DE","region":"SL","date":"2023-08-15","description":"Mariä Himmelfahrt","type":"RF","notes":""}
```
applies also to region `BY`.

See https://www.feiertage-bayern.de/feiertage/2024

**Comment by lauft** [comment]
Thanks for your input ❤️
