### ISSUE TITLE
Add Juneteenth to en-US

### ISSUE THREAD

**Issue by dstark** [GothenburgBitFactory/holidata#114]
Add 19 June annually for en-US as a holiday for `Juneteenth National Independence Day` ([details](https://www.nps.gov/subjects/npscelebrates/juneteenth.htm)).

**Comment by lauft** [comment]
Thanks for pointing this out. PR #115 implements the federal holidays, including Juneteenth.

**Comment by dstark** [comment]
> Thanks for pointing this out. PR #115 implements the federal holidays, including Juneteenth.

Even better. Thanks so much!
