### ISSUE TITLE
Add locale for sv-SE

### ISSUE THREAD

**Issue by lauft** [GothenburgBitFactory/holidata#19]
The following locale needs to be verified/completed:
```
class sv_SE(Locale):
    """
    01-01: [NF] Nyårsdagen
    01-06: [NRF] Trettondedag jul
    04-30: [NF] Valborgmässoafton
    05-01: [NF] Första maj
    06-06: [NF] Nationaldagen
    12-24: [NRF] Julafton
    12-25: [NRF] Juldagen
    12-26: [NRF] Annandag jul
    12-31: [NF] Nyårsafton
    : [NRV] Långfredagen
    : [NRV] Påskdagen
    : [NRV] Annandag påsk
    : [NRV] Kristi Himmelsfärdsdag
    : [NRV] Pingstdagen
    : [NV] Midsommarafton
    : [NV] Midsommardagen
    : [NV] Alla Helgons Dag
    """

    locale = "sv-SE"
    easter_type = EASTER_WESTERN
```
Checklist:
* Are all holidays (i.e. days "which are defined by law on which business or work are suspended or reduced") listed? Can you provide the legal sources which define the holidays?
* Is the spelling correct? Can you maybe provide a translation?
* Are the fixed dates `<month>-<day>` correct?
* If a holiday has a variable date: Is the algorithm to calculate it correct/can you provide it if missing? If it depends on the easter date: Is it the western or orthodox easter date?
* If a holiday is proclaimed by the government: Can you provide the source?
* Are holidays moved to a different date, e.g. if they fall on a saturday/sunday/...? 
* Are holidays observed on a different date (is there a substitute holiday), e.g. if they fall on a saturday/sunday/...?
* Are the flags correct? (`N` = national holiday, defined by law, `R` = holiday with religious background, `F` = holiday with fixed date, `V` = holiday with variable date)
* Have there been any holidays renamed/deleted/created since 2011? If yes, which ones and since when?

**Comment by pxtimes3** [comment]
The days which are not holidays (as mandated by law) are as follows:

> Valborgsmässoafton, Julafton, Midsommarafton, Nyårasfton

See: http://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-1989253-om-allmanna-helgdagar_sfs-1989-253

Pingstdagen is always on a sunday. So it's always considered a holiday.

`class sv_SE(Locale):
    """
    01-01: [NF] Nyårsdagen
    01-06: [NRF] Trettondedag jul
    05-01: [NF] Första maj
    06-06: [NF] Nationaldagen
    12-25: [NRF] Juldagen
    12-26: [NRF] Annandag jul
    : [NRV] Långfredagen
    : [NRV] Påskdagen
    : [NRV] Annandag påsk
    : [NRV] Kristi Himmelsfärdsdag
    : [NRV] Pingstdagen
    : [NV] Midsommardagen
    : [NV] Alla Helgons Dag
    """

    locale = "sv-SE"
    easter_type = EASTER_WESTERN`
