### ISSUE TITLE
Add locale for pt-PT

### ISSUE THREAD

**Issue by lauft** [GothenburgBitFactory/holidata#20]
The following locale needs to be verfied/completed:
```
class pt_PT(Locale):
    u"""
    01-01: [NF] Ano Novo
    04-25: [NF] Dia da Liberdade
    05-01: [NF] Dia do Trabalhador
    06-10: [NF] Dia de Portugal
    08-15: [NF] Assunção de Nossa Senhora
    10-05: [NF] Implantação da República
    11-01: [NF] Todos os Santos
    12-01: [NF] Restauração da Independência
    12-08: [NF] Imaculada Conceição
    12-25: [NF] Natal
    : [NRV] Carnaval
    : [NRV] Sexta-feira Santa
    : [NRV] Páscoa
    : [NRV] Corpo de Deus
    """

    locale = "pt-PT"
    easter_type = EASTER_WESTERN
```
Checklist:
* Are all holidays (i.e. days "which are defined by law on which business or work are suspended or reduced") listed? Can you provide the legal sources which define the holidays?
* Is the spelling correct? Can you maybe provide a translation?
* Are the fixed dates `<month>-<day>` correct?
* If a holiday has a variable date: Is the algorithm to calculate it correct? If it depends on the easter date: Is it the western or orthodox easter date?
* If a holiday is proclaimed by the government: Can you provide the source?
* Are holidays moved to a different date, e.g. if they fall on a saturday/sunday/...? 
* Are holidays observed on a different date (is there a substitute holiday), e.g. if they fall on a saturday/sunday/...?
* Are the flags correct? (`N` = national holiday, defined by law, `R` = holiday with religious background, `F` = holiday with fixed date, `V` = holiday with variable date)

**Comment by lldh** [comment]
Hi, I can check this if still needed.

**Comment by lauft** [comment]
> Hi, I can check this if still needed.
Please do! Never mind if you cannot answer all the points of the checklist, every bit is helpful.
