### ISSUE TITLE
Add locale for pt-BR

### ISSUE THREAD

**Issue by lauft** [GothenburgBitFactory/holidata#21]
The following locale needs to be verified/completed:
```
class pt_BR(Locale):
    u"""
    01-01: [NF] Confraternização Universal
    04-21: [NF] Tiradentes
    05-01: [NF] Dia do Trabalho
    09-07: [NF] Independência do Brasil
    10-12: [NRF] Nossa Senhora Aparecida
    11-02: [NRF] Finados
    11-15: [NF] Proclamação da República
    12-25: [NRF] Natal
    : [NRV] Carnaval
    : [NRV] Carnaval
    : [NRV] Sexta-feira Santa
    : [NRV] Páscoa
    : [NRV] Corpus Christi
    """

    locale = "pt-BR"
    easter_type = EASTER_WESTERN
```
Checklist:
* Are all holidays (i.e. days "which are defined by law on which business or work are suspended or reduced") listed? Can you provide the legal sources which define the holidays?
* Is the spelling correct? Can you maybe provide a translation?
* Are the fixed dates `<month>-<day>` correct?
* If a holiday has a variable date: Is the algorithm to calculate it correct/can you provide it if missing? If it depends on the easter date: Is it the western or orthodox easter date?
* If a holiday is proclaimed by the government: Can you provide the source?
* Are holidays moved to a different date, e.g. if they fall on a saturday/sunday/...? 
* Are holidays observed on a different date (is there a substitute holiday), e.g. if they fall on a saturday/sunday/...?
* Are the flags correct? (`N` = national holiday, defined by law, `R` = holiday with religious background, `F` = holiday with fixed date, `V` = holiday with variable date)
* Have there been any holidays renamed/deleted/created since 2011? If yes, which ones and since when?

**Comment by adrianocorrea** [comment]
See #74
