### ISSUE TITLE
Add locale for pl-PL

### ISSUE THREAD

**Issue by lauft** [GothenburgBitFactory/holidata#22]
The following locale needs to be verified/completed:
```
class pl_PL(Locale):
    """
    01-01: [NF] Nowy Rok
    01-06: [NRF] Trzech Króli
    05-01: [NF] Święto Pracy
    05-03: [NF] Święto Konstytucji Trzeciego Maja
    08-15: [NRF] Wniebowzięcie NMP
    11-01: [NRF] Wszystkich Świętych
    11-11: [NF] Święto Niepodległości
    12-25: [NRF] Boże Narodzenie (pierwszy dzień)
    12-26: [NRF] Boże Narodzenie (drugi dzień)
    : [NRV] Wielkanoc
    : [NRV] Poniedziałek Wielkanocny
    : [NRV] Zielone Świątki
    : [NRV] Boże Ciało
    """

    locale = "pl-PL"
    easter_type = EASTER_WESTERN
```
Checklist:
* Are all holidays (i.e. days "which are defined by law on which business or work are suspended or reduced") listed? Can you provide the legal sources which define the holidays?
* Is the spelling correct? Can you maybe provide a translation?
* Are the fixed dates `<month>-<day>` correct?
* If a holiday has a variable date: Is the algorithm to calculate it correct/can you provide it if missing? If it depends on the easter date: Is it the western or orthodox easter date?
* If a holiday is proclaimed by the government: Can you provide the source?
* Are holidays moved to a different date, e.g. if they fall on a saturday/sunday/...? 
* Are holidays observed on a different date (is there a substitute holiday), e.g. if they fall on a saturday/sunday/...?
* Are the flags correct? (`N` = national holiday, defined by law, `R` = holiday with religious background, `F` = holiday with fixed date, `V` = holiday with variable date)

**Comment by sebacyp** [comment]
>    Are all holidays (i.e. days "which are defined by law on which business or work are suspended or reduced") listed?
Yes. This is the correct list of defined by law on which business or work are suspended.
>     Can you provide the legal sources which define the holidays?
The legal source is Obwieszczenie Marszałka Sejmu Rzeczypospolitej Polskiej z dnia 19 grudnia 2014 r. w sprawie ogłoszenia jednolitego tekstu ustawy o dniach wolnych od pracy (http://prawo.sejm.gov.pl/isap.nsf/download.xsp/WDU20150000090/O/D20150090.pdf)

>    Is the spelling correct?
The official spelling (as given in the provided legal source) is:
01-01: [NF] 1 stycznia - Nowy Rok
01-06: [NRF] 6 stycznie - Święto Trzech Króli
05-01: [NF] 1 maja - Święto Państwowe
05-03: [NF] 3 maja - Święto Narodowe Trzeciego Maja
08-15: [NRF] 15 sierpnia - Wniebowzięcie Najświętszej Maryi Panny
11-01: [NRF] 1 listopada - Wszystkich Świętych
11-11: [NF] 11 listopada - Narodowe Święto Niepodległości
12-25: [NRF] 25 grudnia - pierwszy dzień Bożego Narodzenia
12-26: [NRF] 26 grudnia - drugi dzień Bożego Narodzenia
: [NRV] pierwszy dzień Wielkiej Nocy
: [NRV] drugi dzień Wielkiej Nocy
: [NRV] pierwszy dzień Zielonych Świątek
: [NRV] dzień Bożego Ciała

but the first part is a date pronouncation, and nobody says "November, 1st - All Saints Day" only "All Saints Day". The names shown in the original list are the common names.

>    Can you maybe provide a translation?
 Yes.

>    Are the fixed dates <month>-<day> correct?
Yes.

>    If a holiday has a variable date:
>    Is the algorithm to calculate it correct?
I don't see the algorithm but I can provide one.

>    If it depends on the easter date: Is it the western or orthodox easter date?
It's based on western easter date.

>    If a holiday is proclaimed by the government: Can you provide the source?
The legal sources are:
- ustawa z dnia 18 stycznia 1951 roku o dniach wolnych od pracy (Dz. U. z 1951 r. Nr 4, poz.28, z późn. zm.)
- ustawa z dnia 10 stycznia 2018r. o ograniczeniu handlu w niedzielę i święta oraz w niektóre inne dni
- ustawa z dnia 26 czerwca 1974r. Kodeks pracy

>    Are holidays moved to a different date, e.g. if they fall on a saturday/sunday/...?
There are no holidays moved.

>    Are holidays observed on a different date (is there a substitute holiday), e.g. if they fall on a saturday/sunday/...?
If the holiday occures on Saturday, employer must provide substitute holiday (but no fixed nor calculated date is provided).

>    Are the flags correct? (N = national holiday, defined by law, R = holiday with religious background, F = holiday with fixed date, V = holiday with variable date)
Yes, the provided flags are correct.

**Comment by lauft** [comment]
The locale `pl-PL` has been added, data up to 2020 is now available on [holidata.net](https://holidata.net). Thank you for your contribution!
