### ISSUE TITLE
Add locale for fi-FI

### ISSUE THREAD

**Issue by lauft** [GothenburgBitFactory/holidata#30]
The following locale needs to be verified/completed:
```
class fi_FI(Locale):
    """
    01-01: [NF] Uudenvuodenpäivä
    01-06: [NRF] Loppiainen
    05-01: [NF] Vappu
    12-06: [NF] Itsenäisyyspäivä
    12-24: [NRF] Jouluaatto
    12-25: [NRF] Joulupäivä
    12-26: [NRF] 2. joulupäivä
    2 days before Easter: [NRV] Pitkäperjantai
    Easter: [NRV] Pääsiäispäivä
    1 day after Easter: [NRV] 2. pääsiäispäivä
    39 days after Easter: [NRV] Helatorstai
    49 days after Easter: [NRV] Helluntaipäivä
    : [NV] Juhannusaatto
    : [NV] Juhannuspäivä
    : [NV] Pyhäinpäivä
    """

    locale = "fi-FI"
    easter_type = EASTER_WESTERN
```
Checklist:
* Are all holidays (i.e. days "which are defined by law on which business or work are suspended or reduced") listed? Can you provide the legal sources which define the holidays?
* Is the spelling correct? Can you maybe provide a translation?
* Are the fixed dates `<month>-<day>` correct?
* If a holiday has a variable date: Is the algorithm to calculate it correct/can you provide it if missing? If it depends on the easter date: Is it the western or orthodox easter date?
* If a holiday is proclaimed by the government: Can you provide the source?
* Are holidays moved to a different date, e.g. if they fall on a saturday/sunday/...? 
* Are holidays observed on a different date (is there a substitute holiday), e.g. if they fall on a saturday/sunday/...?
* Are the flags correct? (`N` = national holiday, defined by law, `R` = holiday with religious background, `F` = holiday with fixed date, `V` = holiday with variable date)
* Have there been any holidays renamed/deleted/created since 2011? If yes, which ones and since when?

**Comment by anttiheinonen** [comment]
Not sure about the ultimate official source, but https://almanakka.helsinki.fi/en/flag-days-and-holidays-in-finland.html is definately a very reputable one.
All the finnish translations can be found from https://almanakka.helsinki.fi/fi/liputus-ja-juhlapaivat/suomen-kalenterin-juhlapaivat.html, your list looks good to me.

**Comment by lauft** [comment]
Thank you for your input!

I have updated the `fi-FI` locale and it reproduces the available holidata from 2011 to 2018, so it's good to publish. The missing legal sources is a bit dissapointing; the [wiki page](https://fi.wikipedia.org/wiki/Suomen_juhlap%C3%A4iv%C3%A4t) lists [Vuosilomalain 4 §](https://finlex.fi/fi/laki/ajantasa/2005/20050162#L1P4) as a source, but I could not find a distinct listing of holidays there - maybe later then.

From the data I also created the Swedish version (`sv-FI`) as well. 🐦🐦 + 🥌
