### ISSUE TITLE
Add locale for hu-HU

### ISSUE THREAD

**Issue by dhanak** [GothenburgBitFactory/holidata#59]
**Basic information**
* What is the language code according to [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)? **hu**
* What is the country code according to [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2)? **HU**

(please replace `LANG` and `COUNTRY` in the issue title accordingly)

* Provide a list of all holidays, i.e. days "which are defined by law on which business or work are suspended or reduced" **https://www.timeanddate.com/holidays/hungary/**
* Are holidays moved to a different date, e.g. if they fall on a saturday/sunday/...? If yes, which holidays and what is the algorithm? **no**
* Are holidays observed on a different date (is there a substitute holiday), e.g. if they fall on a saturday/sunday/...? If yes, which holidays and what is the algorithm? **no**
* If possible, provide the legal sources which define the holidays. **https://www.timeanddate.com/holidays/hungary/**

**For each holiday**
* What is the official name?
* Is it a regional or nation-wide holiday?
* If regional, what are the regions the holiday is observed in? (Note: currently only regions defined in ISO_3166-2 are supported)
* Is it a fixed or variable date?
* If fixed, provide the date in format `MM-DD`
* If a holiday has a variable date: What is the algorithm to calculate it (e.g. `nth <weekday>/<day> in <month>`,...? If it depends on the easter date: Is it the western or orthodox easter date?
* If the holiday is proclaimed by the government: Can you provide the source?

**Comment by lauft** [comment]
@dhanak Just linking to timeanddate.com is not doing the job. Besides that, this website is not the _legal source which define the holidays_, this would be a government website or a reference to the respective legal documents.

**Comment by dhanak** [comment]
Point taken.

1. There is no single legal source which lists all public holidays. Wikipedia, among other sites, gives a thorough list, though: https://en.wikipedia.org/wiki/Public_holidays_in_Hungary.

2. In addition to these, when a public holiday falls on a Tuesday or a Wednesday, a special decree swaps the preceding Monday or the following Friday (respectively) with a not too distant Saturday, thus creating a four day long weekend. (In recent years, Dec 24 is also made a holiday.) The decree for 2020 can be found here: https://net.jogtar.hu/jogszabaly?docid=A1900007.PM (Hungarian only), the decree for 2021 I only found in PDF form here: https://magyarkozlony.hu/dokumentumok/fb64e975308d6b271d7d44b6e4802a3010a65fdf/letoltes, pp. 35. The dates listed in these decrees are the following:
- Fri, Aug 21 2020 (holiday), swapped with Sat, Aug 29 (workday)
- Sat, Dec 12 2020 (workday), swapped with Thu, Dec 24 (holiday)
- Sat, Dec 11 2021 (workday), swapped with Fri, Dec 24 (holiday)

HTH.

**Comment by lauft** [comment]
> There is no single legal source which lists all public holidays.

In general, it would be helpful to compile all the individual sources, for documentation and for reference.

Wikipedia references the national constitution which mentions 3 holidays
* `03-15`, _Nemzeti ünnep_ (National Day, 1848–49 Revolution and War of Independence)
* `10-23`, _Az államalapítás ünnepe_ (State Foundation Day)
* `08-20`, _Nemzeti ünnep_ (National Day, 1956 Revolution and War of Independence)

which leaves
* `01-01`, _Újév_ (New Year's Day)
* `05-01`, _A munka ünnepe_ (Labour Day)
* `11-01`, _Mindenszentek_ (All Saints Day)
* `12-25`, _Karácsony_ (Christmas Day)
* `12-26`, _Karácsony másnapja_ (Second Day of Christmas)
* `Easter-2`, _Nagypéntek_ (Good Friday)
* `Easter+1`, _Húsvéthétfő_ (Easter Monday)
* `Easter+50`, _Pünkösdhétfő_ (Pentecost Monday)

to be documented. Good Friday, it is mentioned, has only been a public holiday since 2017 and also Wikipedia say "citation needed". The sources are even more important for all those swaps which happened since 2011.

Of course, the current and future years have top priority, but Holidata provides the holiday data of all its locales since 2011 and it would be a shame if Hungary became the exception. In any case, we can start from here and update later

> In addition to these, when a public holiday falls on a Tuesday or a Wednesday, a special decree swaps the preceding Monday or the following Friday (respectively) with a not too distant Saturday, thus creating a four day long weekend.

Is there a specific date/deadline when those decrees are issued each year? So we know when to check for updates and incorporate them into the locale.

Another question: Both, `03-15` and `08-20` are mentioned as _Nemzeti ünnep_ on the Wikipedia page. Is this the official name of those holidays? The constitution also does not name a specific name, only their purpose.

**Comment by lauft** [comment]
@dhanak I have compiled the sources into a first draft (see #62). It would be nice if you could review it for errors and typos.

Some questions:
* Are `Húsvét` and `Húsvéthétfő`  the official names for `Easter` and `Easter Monday`?
* Are `Pünkösd` and `Pünkösdhétfő` the official names for `Pentecost` and `Pentecost Monday`?
* How are the decreed holidays named?
* Currently the decreed holidays get the note "Swapped with <date>", but I think this should be in Hungarian.

**Comment by dhanak** [comment]
Hello @lauft,

Thanks for the thorough comments! Here are my remarks.

> In general, it would be helpful to compile all the individual sources, for documentation and for reference.

I will try to collect as many of them as possible over the next weekend.

> Wikipedia references the national constitution which mentions 3 holidays
> 
> * `03-15`, _Nemzeti ünnep_ (National Day, 1848–49 Revolution and War of Independence)
> * `10-23`, _Az államalapítás ünnepe_ (State Foundation Day)
> * `08-20`, _Nemzeti ünnep_ (National Day, 1956 Revolution and War of Independence)

Watch out, you've got 10-23 and 08-20 swapped. 08-20 is the Sate Foundation Day, and 10-23 is the 1956 Revolution Remembrance Day.
 
> to be documented. Good Friday, it is mentioned, has only been a public holiday since 2017 and also Wikipedia says "citation needed" here. Those sources are even more important for all those swaps which happened since 2011.

Yes, it's a farily new addition to the list of state holidays. I will dig up the statute on this one.

> Is there a specific date/deadline when those decrees are issued each year? So we know when to check for updates and incorporate them into the locale.

I'm not sure about a deadline, but this legislation usually happens for a given calendar some time during the summer of the previous year. (I see dates from May, June, and even August of earlier years.)

> Another question: Both, `03-15` and `08-20` are mentioned as _Nemzeti ünnep_ on the Wikipedia page. Is this the official name of those holidays? The constitution also does not name a specific name, only their purpose.

Yes, these are days of remembrance, honoring the memory of an important historical moment, but they don't have a short, commonly used name (or any official name that I know of), like the others. 03-15 is the day of the Hungarian Revolution of 1848, and 08-20 is, as mentioned above, is State Foundation Day, but they are more commonly referred to by the dates themselves.

> Are Húsvét and Húsvéthétfő the official names for Easter and Easter Monday?

Yes.

> Are Pünkösd and Pünkösdhétfő the official names for Pentecost and Pentecost Monday?

Yes.

> How are the decreed holidays named?

They don't have names. They are simply called "non-working day" (munkaszüneti nap), just like ordinary Saturdays, since these days are always swapped with a nearby Saturday.

I'll get back later with the legislation references.

HTH,
David

**Comment by dhanak** [comment]
> @dhanak I have compiled the sources into a first draft (see #62). It would be nice if you could review it for errors and typos.

I just did. HTH.

**Comment by lauft** [comment]
@dhanak I updated the PR. I guess it will need one final review to make sure I spelled everything correctly... 😄

**Comment by lauft** [comment]
Merged. Thanks again for your help. 👍🏻 
I hope I can count on you when the holidays for 2022 decreed... 🙂
