### ISSUE TITLE
Add locale for en-US (Federal Reserve Holiday Calendar)

### ISSUE THREAD

**Issue by walterjwhite** [GothenburgBitFactory/holidata#64]
**Basic information**
* What is the language code according to [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)?
en

* What is the country code according to [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2)?
US

https://www.federalreserve.gov/aboutthefed/k8.htm

**Comment by lauft** [comment]
There is already a locale `en-US` which serves all the holidays (and more) listed on the Federal Reserve website.

**Comment by walterjwhite** [comment]
Yes, I was hoping for it to be split so I could have a simpler conf - I will write a hook to exclude the others.

**Comment by lauft** [comment]
Is there a reason you would need such a subset? Do the other holidays (defined by state and federal law) not apply to you?
If you could describe your specific use case we could work out a solution...

**Comment by walterjwhite** [comment]
Yes, the other holidays do not apply to me (for work).  It wouldn't be much effort for me to maintain the difference myself, small effort, once / year.

I am thinking long-term what I would like to do is:
Leverage different calendars for specific projects (work, home, travel, sick-days, co-workers schedules, etc.).

My work projects should default to a work calendar, but it might also be nice to show an overall calendar and how that impacts my work or which tasks I choose to do because of upcoming holidays.  It might also be beneficial to have other holidays for my co-workers if they're located somewhere else (especially if the project I'm working on requires a lot of interaction with them).  With the additional calendars, perhaps I could also create another calendar which separately tracks my sick days.

**Comment by lauft** [comment]
Sounds a bit out of scope for holidata to me. In the longterm holidata may receive more tags or other means to ease filtering.
I am closing this, but feel free to share your ideas in the future.
