### ISSUE TITLE
Add locale for sl-SI

### ISSUE THREAD

**Issue by terrible-solver** [GothenburgBitFactory/holidata#68]
https://en.wikipedia.org/wiki/Public_holidays_in_Slovenia
https://www.gov.si/en/topics/national-holidays/ official government link

List of fixed nationwide work free holidays:
- 01-01 "New Year's Day"
- 01-02 "New Year's Day"
- 02-08 "Prešeren Day"
- 04-27 "Day of Uprising Against Occupation"
- 05-01 "Labour Day"
- 05-02 "Labour Day"
- 06-25 "Statehood Day"
- 08-15 "Feast of the Assumption"
- 10-31 "Reformation Day"
- 11-01 "Day of Remembrance for the Dead"
- 12-25 "Christmas Day"
- 12-26 "Independence and Unity Day"

List of moving holidays:
- Easter Sunday (western date)
- Easter Monday (western date)
- Whit Sunday https://en.wikipedia.org/wiki/Pentecost (western date)

**Comment by lauft** [comment]
Done in #78
