### ISSUE TITLE
Error in locale fr-FR

### ISSUE THREAD

**Issue by sebhz** [GothenburgBitFactory/holidata#71]
There is a typo in the fr-FR locale (year 2020 and 2021 checked).
Ascension holiday is currently written ascen<ins>c</ins>ion (with a "c"). It shoud be written ascen<ins>s</ins>ion (with an "s")

**Comment by pbeckingham** [comment]
Resolved. Thank you.

**Comment by lauft** [comment]
Holidata files on holidata.net froom 2011 to 2021 have been updated as well. Merci! 🙂
