### ISSUE TITLE
Add locale for sl-SI

### ISSUE THREAD

**Issue by dejande** [GothenburgBitFactory/holidata#77]
**Basic information**
* What is the language code according to [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)? sl
* What is the country code according to [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2)? SI

(please replace `LANG` and `COUNTRY` in the issue title accordingly)

* Provide a list of all holidays, i.e. days "which are defined by law on which business or work are suspended or reduced"
* Are holidays moved to a different date, e.g. if they fall on a saturday/sunday/...? If yes, which holidays and what is the algorithm?
* Are holidays observed on a different date (is there a substitute holiday), e.g. if they fall on a saturday/sunday/...? If yes, which holidays and what is the algorithm?
* If possible, provide the legal sources which define the holidays.

https://www.gov.si/en/topics/national-holidays/

**For each holiday**
* What is the official name?
* Is it a regional or nation-wide holiday?
* If regional, what are the regions the holiday is observed in? (Note: currently only regions defined in ISO_3166-2 are supported)
* Is it a fixed or variable date?
* If fixed, provide the date in format `MM-DD`
* If a holiday has a variable date: What is the algorithm to calculate it (e.g. `nth <weekday>/<day> in <month>`,...? If it depends on the easter date: Is it the western or orthodox easter date?
* If the holiday is proclaimed by the government: Can you provide the source?

| Name  | Regional (R) vs nation-wide (N) | fixed (F) / variable (V) | Date | work-free day Y/N | Source |
| ------------- | ------------- | ------------- |  ------------- | ------------- | ------------- |
| New Year Holiday  | N  | F  | 01-01  | Y  | *  |
| New Year Holiday  | N  | F  | 01-02  | Y  | *  |
| Prešeren Day, the Slovenian Cultural Holiday  | N  | F  | 02-08  | Y  | *  |
| Day of Uprising Against the Occupation  | N  | F  | 04-27  | Y  | *  |
| Labour Day  | N  | F  | 05-01  | Y  | *  |
| Labour Day  | N  | F  | 05-02  | Y  | *  |
| Primož Trubar Day  | N  | F  | 06-08  | N  | *  |
| Statehood Day  | N  | F  | 06-25  | Y  | *  |
| Unification of Prekmurje Slovenes with the Mother Nation  | N  | F  | 08-17  | N  | *  |
| Return of Primorska to the Motherland  | N  | F  | 09-15  | N  | *  |
| Slovenian Sports Day  | N  | F  | 09-23  | N  | *  |
| Sovereignty Day  | N  | F  | 10-25  | N  | *  |
| Day of Remembrance for the Dead  | N  | F  | 11-01  | Y  | *  |
| Rudolf Maister Day  | N  | F  | 11-23  | N  | *  |
| Independence and Unity Day  | N  | F  | 12-26  | Y  | *  |
| Easter Sunday  | N  | V  | western  | Y  | *  |
| Easter Monday  | N  | V  | western  | Y  | *  |
| Whit Sunday  | N  | V  | western  | Y  | *  |
| Feast of the Assumption  | N  | F  | 08-15  | Y  | *  |
| Reformation Day  | N  | F  | 10-31  | Y  | *  |
| Christmas Day  | N  | F  | 12-25  | Y  | *  |

\* https://www.gov.si/en/topics/national-holidays/

**Comment by lauft** [comment]
Thanks for the input. 👍🏻 

Could you provide the original names of the holidays? Otherwise this would be the `en-SI` locale.
Also it would be good if you could dig up the respective law(s) which define the holidays. I found http://www.pisrs.si/Pis.web/ where the "the online version of the Government Gazette of the Republic of Slovenia" seems to be published. I guess this could be the place to find those.

Another remark: Holidata will only list the "defined by law on which business or work are suspended or reduced", i.e. non-workfree holidays will be omitted, because the main consumers Timewarrior and Taskwarrior use those to determine workfree time.

**Comment by lauft** [comment]
@dejande I have created #78 with a first draft.

**Comment by dejande** [comment]
> Could you provide the original names of the holidays? Otherwise this would be the `en-SI` locale.

Oh yes, that is actually en-SI. Let me also prepare sl-SI.

>Also it would be good if you could dig up the respective law(s) which define the holidays. I found http://www.pisrs.si/Pis.web/ where the "the online version of the Government Gazette of the Republic of Slovenia" seems to be published. I guess this could be the place to find those.

Sure. Here it is:
http://www.pisrs.si/Pis.web/pregledPredpisa?id=ZAKO865#

> Another remark: Holidata will only list the "defined by law on which business or work are suspended or reduced", i.e. non-workfree holidays will be omitted, because the main consumers Timewarrior and Taskwarrior use those to determine workfree time.

Undersood.

**Comment by dejande** [comment]
| Name  | Regional (R) vs nation-wide (N) | fixed (F) / variable (V) | Date | work-free day Y/N | Source |
| ------------- | ------------- | ------------- |  ------------- | ------------- | ------------- |
| novo leto  | N  | F  | 01-01  | Y  | *  |
| novo leto  | N  | F  | 01-02  | Y  | *  |
| Prešernov dan, slovenski kulturni praznik  | N  | F  | 02-08  | Y  | *  |
| dan upora proti okupatorju  | N  | F  | 04-27  | Y  | *  |
| praznik dela | N  | F  | 05-01  | Y  | *  |
| praznik dela | N  | F  | 05-02  | Y  | *  |
| dan Primoža Trubarja | N  | F  | 06-08  | N  | *  |
| dan državnosti  | N  | F  | 06-25  | Y  | *  |
| združitev prekmurskih Slovencev z matičnim narodom | N  | F  | 08-17  | N  | *  |
| vrnitev Primorske k matični domovini  | N  | F  | 09-15  | N  | *  |
| dan slovenskega športa | N  | F  | 09-23  | N  | *  |
| dan suverenosti | N  | F  | 10-25  | N  | *  |
| dan spomina na mrtve | N  | F  | 11-01  | Y  | *  |
| dan Rudolfa Maistra | N  | F  | 11-23  | N  | *  |
| dan samostojnosti in enotnosti | N  | F  | 12-26  | Y  | *  |
| velikonočna nedelja | N  | V  | western  | Y  | *  |
| velikonočni ponedeljek | N  | V  | western  | Y  | *  |
| binkošti | N  | V  | western  | Y  | *  |
| Marijino vnebovzetje | N  | F  | 08-15  | Y  | *  |
| dan reformacije | N  | F  | 10-31  | Y  | *  |
| božič | N  | F  | 12-25  | Y  | *  |

\* https://www.gov.si/teme/drzavni-prazniki-in-dela-prosti-dnevi/
