### ISSUE TITLE
Error in locale en-GB[, year 2022]

### ISSUE THREAD

**Issue by richardfieldsend** [GothenburgBitFactory/holidata#85]
**UK holidata Issue for 2022**  
* Affects en-GB locale (United Kingdom)
* Non-standard Bank Holidays in 2022 because this year is the Queen's Platinum Jubilee. 

**Expected behavior**  
Normal Spring Bank Holiday date would be: 30th May 2022
Moved to 2nd June 2022
Additional holiday for Jubilee on 3rd June 2022

Rest of the year appears to be fine. 

Holidays for 2023 (which appear not to have downloaded) will be:

en-GB:
   2023_01_02 = New Year's Day
   2023_04_07 = Good Friday
   2023_04_10 = Easter Monday
   2023_05_01 = Early May bank holiday
   2023_05_29 = Spring bank holiday
   2023_08_28 = Summer bank holiday
   2023_12_25 = Christmas Day
   2023_12_26 = Boxing Day

** Comments
There are calls to make the extra Bank Holiday permanent, but this hasn't been discussed in government yet. There is a page of upcoming holidays which can be viewed here: 

https://www.gov.uk/bank-holidays

**Comment by lauft** [comment]
Thanks for reporting. The holidata for 2022 has been updated.
